using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace FlowCore.Generators;

[Generator]
public sealed class DiRegistrationGenerator : IIncrementalGenerator
{
    private const string CommandHandlerType = "FlowCore.Core.Interfaces.ICommandHandler`2";
    private const string QueryHandlerType = "FlowCore.Core.Interfaces.IQueryHandler`2";
    private const string EventHandlerType = "FlowCore.Core.Interfaces.IEventHandler`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 },
                transform: static (ctx, _) => GetHandlerDIType(ctx))
            .Where(static info => info is not null)
            .Collect();

        context.RegisterSourceOutput(handlerTypes, GenerateRegistration);
    }

    private static string? GetHandlerDIType(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        var typeSymbol = semanticModel.GetDeclaredSymbol(classDecl);

        if (typeSymbol is null) return null;

        foreach (var iface in typeSymbol.AllInterfaces)
        {
            if (!iface.IsGenericType) continue;

            var openGeneric = iface.ConstructUnboundGenericType();
            var openGenericName = openGeneric.ToDisplayString();

            if (openGenericName is CommandHandlerType or QueryHandlerType or EventHandlerType)
            {
                return typeSymbol.ToDisplayString();
            }
        }

        return null;
    }

    private static void GenerateRegistration(SourceProductionContext context, ImmutableArray<string?> handlerTypes)
    {
        var types = handlerTypes.Where(t => t is not null).Cast<string>().Distinct().ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace FlowCore.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class GeneratedDiRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        public static void RegisterHandlers(IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var type in types)
        {
            sb.AppendLine($"            services.AddScoped<{type}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedDiRegistration.g.cs", sb.ToString());
    }
}
