using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace FlowCore.Generators;

[Generator]
public sealed class DispatcherGenerator : IIncrementalGenerator
{
    private const string CommandHandlerType = "FlowCore.Core.Interfaces.ICommandHandler`2";
    private const string QueryHandlerType = "FlowCore.Core.Interfaces.IQueryHandler`2";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 },
                transform: static (ctx, _) => GetHandlerDispatchInfo(ctx))
            .Where(static info => info is not null)
            .Collect();

        context.RegisterSourceOutput(handlerTypes, GenerateDispatcher);
    }

    private static DispatchInfo? GetHandlerDispatchInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        var typeSymbol = semanticModel.GetDeclaredSymbol(classDecl);

        if (typeSymbol is null) return null;

        foreach (var iface in typeSymbol.AllInterfaces)
        {
            if (!iface.IsGenericType) continue;

            var openGeneric = iface.ConstructUnboundGenericType();
            var openGenericName = openGeneric.ToDisplayString();

            if (openGenericName == CommandHandlerType)
            {
                var args = iface.TypeArguments;
                return new DispatchInfo(
                    args[0].Name, args[0].ToDisplayString(),
                    args[1].ToDisplayString());
            }
            if (openGenericName == QueryHandlerType)
            {
                var args = iface.TypeArguments;
                return new DispatchInfo(
                    args[0].Name, args[0].ToDisplayString(),
                    args[1].ToDisplayString());
            }
        }

        return null;
    }

    private static void GenerateDispatcher(SourceProductionContext context, ImmutableArray<DispatchInfo?> handlers)
    {
        var valid = handlers
            .Where(h => h is not null)
            .Cast<DispatchInfo>()
            .GroupBy(h => h.RequestFullName)
            .Select(g => g.First())
            .ToList();

        if (valid.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace FlowCore.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class GeneratedDispatcher");
        sb.AppendLine("    {");
        sb.AppendLine("        public static async ValueTask<object?> DispatchAsync(");
        sb.AppendLine("            object request,");
        sb.AppendLine("            IServiceProvider services,");
        sb.AppendLine("            CancellationToken cancellationToken)");
        sb.AppendLine("        {");

        bool first = true;
        foreach (var h in valid)
        {
            if (first)
            {
                sb.AppendLine($"            if (request is {h.RequestFullName} {h.RequestVar})");
                first = false;
            }
            else
            {
                sb.AppendLine($"            else if (request is {h.RequestFullName} {h.RequestVar})");
            }
            sb.AppendLine("            {");
            sb.AppendLine($"                var handler = services.GetRequiredService<I{h.RequestName}Handler>();");
            sb.AppendLine($"                return await handler.HandleAsync({h.RequestVar}, cancellationToken);");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            throw new InvalidOperationException($\"No handler found for {request.GetType().Name}\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedDispatcher.g.cs", sb.ToString());
    }

    private sealed record DispatchInfo(
        string RequestName,
        string RequestFullName,
        string ResponseFullName)
    {
        public string RequestVar => $"req{RequestName}";
    }
}
