using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace FlowCore.Generators;

[Generator]
public sealed class HandlerRegistryGenerator : IIncrementalGenerator
{
    private const string CommandHandlerAttribute = "FlowCore.Core.Interfaces.ICommandHandler`2";
    private const string QueryHandlerAttribute = "FlowCore.Core.Interfaces.IQueryHandler`2";
    private const string EventHandlerAttribute = "FlowCore.Core.Interfaces.IEventHandler`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateType(node),
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null)
            .Collect();

        context.RegisterSourceOutput(handlerTypes, GenerateRegistry);
    }

    private static bool IsCandidateType(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 };
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        var typeSymbol = semanticModel.GetDeclaredSymbol(classDecl);

        if (typeSymbol is null) return null;

        foreach (var iface in typeSymbol.AllInterfaces)
        {
            if (!iface.IsGenericType) continue;

            var openGeneric = iface.ConstructUnboundGenericType();
            var openGenericName = openGeneric.ToDisplayString();

            if (openGenericName == CommandHandlerAttribute)
            {
                var args = iface.TypeArguments;
                return new HandlerInfo(typeSymbol.Name, typeSymbol.ToDisplayString(),
                    args[0].Name, args[0].ToDisplayString(),
                    args[1].ToDisplayString(), "Command");
            }
            if (openGenericName == QueryHandlerAttribute)
            {
                var args = iface.TypeArguments;
                return new HandlerInfo(typeSymbol.Name, typeSymbol.ToDisplayString(),
                    args[0].Name, args[0].ToDisplayString(),
                    args[1].ToDisplayString(), "Query");
            }
            if (openGenericName == EventHandlerAttribute)
            {
                var args = iface.TypeArguments;
                return new HandlerInfo(typeSymbol.Name, typeSymbol.ToDisplayString(),
                    args[0].Name, args[0].ToDisplayString(),
                    "System.Threading.Tasks.Task", "Event");
            }
        }

        return null;
    }

    private static void GenerateRegistry(SourceProductionContext context, ImmutableArray<HandlerInfo?> handlers)
    {
        var valid = handlers.Where(h => h is not null).Cast<HandlerInfo>().ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using FlowCore;");
        sb.AppendLine();
        sb.AppendLine("namespace FlowCore.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class GeneratedHandlerRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        public static readonly IReadOnlyList<HandlerDescriptor> Handlers = new List<HandlerDescriptor>");
        sb.AppendLine("        {");

        foreach (var h in valid)
        {
            sb.AppendLine($"            new HandlerDescriptor");
            sb.AppendLine("            {");
            sb.AppendLine($"                HandlerType = typeof({h.FullTypeName}),");
            sb.AppendLine($"                RequestType = typeof({h.RequestFullName}),");
            sb.AppendLine($"                ResponseType = {(h.Kind == "Event" ? "null" : $"typeof({h.ResponseFullName})")},");
            sb.AppendLine($"                Kind = HandlerKind.{h.Kind}");
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedHandlerRegistry.g.cs", sb.ToString());
    }

    private sealed record HandlerInfo(
        string Name,
        string FullTypeName,
        string RequestName,
        string RequestFullName,
        string ResponseFullName,
        string Kind);
}
